# Generated by Django 5.1.2 on 2024-10-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_trades', models.IntegerField()),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_date', models.DateField(null=True)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shares', models.IntegerField()),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('exit_reason', models.CharField(max_length=50, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtestresults')),
            ],
        ),
    ]
